# options.yaml
sha:
  - option: "SHA-2 256"
    description: "Produit une empreinte de 256 bits."
    show: true
  - option: "SHA-2 384"
    description: "Produit une empreinte de 384 bits."
    show: true
  - option: "SHA-2 512"
    description: "Produit une empreinte de 512 bits."
    show: true
  - option: "SHA-3 256"
    description: "Produit une empreinte de 256 bits."
    show: true
  - option: "SHA-3 384"
    description: "Produit une empreinte de 384 bits."
    show: true
  - option: "SHA-3 512"
    description: "Produit une empreinte de 512 bits."
    show: true
aes:
  - option: '128 bits'
    description: "Offre un niveau de sécurité de 128 bits."
    show: true
  - option: '192 bits'
    description: "Offre un niveau de sécurité de 192 bits."
    show: true
  - option: '256 bits'
    description: "Offre un niveau de sécurité de 256 bits."
    show: true
rsa:
  - option: "1024 bits"
    description: "Equivaut à un niveau de sécurité de 80 bits."
    show: true
  - option: "2048 bits"
    description: "Equivaut à un niveau de sécurité de 112 bits."
    show: false
  - option: "3072 bits"
    description: "Equivaut à un niveau de sécurité de 128 bits."
    show: true
  - option: "7680 bits"
    description: "Equivaut à un niveau de sécurité de 192 bits."
    show: true
  - option: "15360 bits"
    description: "Equivaut à un niveau de sécurité de 256 bits."
    show: true
ecc:
  - option: "SECP 256 R1"
    description: "Equivaut à un niveau de sécurité de 128 bits."
    show: true
  - option: "SECP 384 R1"
    description: "Equivaut à un niveau de sécurité de 192 bits."
    show: true
  - option: "SECP 512 R1"
    description: "Equivaut à un niveau de sécurité de 256 bits."
    show: true
chacha20:
  - option: '128 bits'
    description: "Offre un niveau de sécurité de 128 bits."
    show: true
  - option: '192 bits'
    description: "Offre un niveau de sécurité de 192 bits."
    show: true
  - option: '256 bits'
    description: "Offre un niveau de sécurité de 256 bits."
    show: true
kyber:
  - option: 'ML-KEM-512'
    description: "Combine AES 128 bits + Kyber pour offrir un niveau de sécurité de 128 bits."
    show: true
  - option: 'ML-KEM-768'
    description: "Combine AES 192 bits + Kyber pour offrir un niveau de sécurité de 192 bits."
    show: true
  - option: 'ML-KEM-1024'
    description: "Combine AES 256 bits + Kyber pour offrir un niveau de sécurité de 256 bits."
    show: true
ntru:
  - option: 'NTRU-2048-509'
    description: "Offre un niveau de sécurité de 128 bits."
    show: true
  - option: 'NTRU-2048-677'
    description: "Offre un niveau de sécurité de 192 bits."
    show: true
  - option: 'NTRU-4096-821'
    description: "Offre un niveau de sécurité de 256 bits."
    show: true